server:
  port: 5602

spring:
  application:
    name: gateWayService
  boot:
    admin:
      client:
        url: http://192.168.200.135:7000
  cloud:
    gateway:
      loadbalancer:
        use404: true
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
      - id: service_to_user
        uri: lb://userimp
        order: 8000
        predicates:
        - Path=/user/**
        filters:
        - StripPrefix=1
      - id: service_to_user
        uri: http://192.168.10.112:8203
        order: 8000
        predicates:
        - Path=/user2/**
        filters:
        - StripPrefix=1
      - id: service_to_order
        uri: lb://orderimp
        order: 8000
        predicates:
        - Path=/order/**
        filters:
        - StripPrefix=1
      - id: service_to_pay
        uri: lb://payimp
        order: 8000
        predicates:
        - Path=/pay/**
        filters:
        - StripPrefix=1
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
       defaultZone: http://192.168.200.85:6801/eureka/,http://192.168.200.135:6802/eureka/,http://192.168.200.136:6803/eureka/
  instance:
    prefer-ip-address: true